### ISSUE TITLE
Terraform 0.13.5 Crashes

### ISSUE THREAD

**Issue by petewilcock** [skyscrapr/terraform-provider-cloudability#16]
Hey there - I've been able to install the provider with Terraform 0.13.5 but not getting anywhere with the creation of resources. 

Example view definition:

```
resource "cloudability_view" "test" {
  provider = "cloudability"
  title = "Test"
  shared_with_organization = true
  filter {
    field = "vendor_account_name"
    comparator = "=="
    value = "Test"
  }
}
```
Tried with several permutations, simplifying definition, etc. but always gets the same crash. 

Error on attempting to apply:

```
cloudability_view.test: Creating...

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: [signal 0xc0000005 code=0x0 addr=0x48 pc=0xe57eba]
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: goroutine 28 [running]:
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: github.com/skyscrapr/cloudability-sdk-go/cloudability.(*v3Endpoint).doRequest(0xc000092568, 0xc000120100, 0xedd800, 0xc0002ba7e0, 0x0, 0x0, 0x0)
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     github.com/skyscrapr/cloudability-sdk-go@v0.0.3/cloudability/client.go:162 +0x12a
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: github.com/skyscrapr/cloudability-sdk-go/cloudability.(*Client).do(0xc000878540, 0x13a5ca0, 0xc000092570, 0x10dbaae, 0x4, 0x0, 0x0, 0xeddb00, 0xc0007b78b0, 0xedd800, ...)
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     github.com/skyscrapr/cloudability-sdk-go@v0.0.3/cloudability/client.go:125 +0x120
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: github.com/skyscrapr/cloudability-sdk-go/cloudability.(*Client).post(...)
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     github.com/skyscrapr/cloudability-sdk-go@v0.0.3/cloudability/client.go:108
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: github.com/skyscrapr/cloudability-sdk-go/cloudability.(*ViewsEndpoint).NewView(0xc000092570, 0xc000153f10, 0x1, 0xc000092560, 0x1)
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     github.com/skyscrapr/cloudability-sdk-go@v0.0.3/cloudability/views.go:63 +0x122
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: github.com/skyscrapr/terraform-provider-cloudability/cloudability.resourceViewCreate(0xc000153810, 0x10b68a0, 0xc000878540, 0x2, 0x1b7ed00)
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     github.com/skyscrapr/terraform-provider-cloudability/cloudability/resource_view.go:81 +0x303
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000196b40, 0xc0007b75e0, 0xc00030de60, 0x10b68a0, 0xc000878540, 0xf7c301, 0xc000530b88, 0xc000553a40)
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:310 +0x36c
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00003ca00, 0xc0003eba38, 0xc0007b75e0, 0xc00030de60, 0xc0001b01a8, 0xc0000923a0, 0xf7e0a0)
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:294 +0xa0
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000071c8, 0x13ac6e0, 0xc000667b30, 0xc000152fc0, 0xc0000071c8, 0xc000667b30, 0xc000255ba0)
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:885 +0x8bb
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x109a880, 0xc0000071c8, 0x13ac6e0, 0xc000667b30, 0xc000086ae0, 0x0, 0x13ac6e0, 0xc000667b30, 0xc000336140, 0x12c)
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x21e
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00033e000, 0x13b9420, 0xc000578780, 0xc000014100, 0xc00052e180, 0x1b421a0, 0x0, 0x0, 0x0)
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     google.golang.org/grpc@v1.30.0/server.go:1171 +0x511
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: google.golang.org/grpc.(*Server).handleStream(0xc00033e000, 0x13b9420, 0xc000578780, 0xc000014100, 0x0)
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     google.golang.org/grpc@v1.30.0/server.go:1494 +0xcd4
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000306240, 0xc00033e000, 0x13b9420, 0xc000578780, 0xc000014100)
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     google.golang.org/grpc@v1.30.0/server.go:834 +0xa8
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-11-11T12:16:16.033Z [DEBUG] plugin.terraform-provider-cloudability_v0.0.6.exe:     google.golang.org/grpc@v1.30.0/server.go:832 +0x20b
2020-11-11T12:16:16.034Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020/11/11 12:16:16 [DEBUG] cloudability_view.tbu_test: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/11/11 12:16:16 [TRACE] eval: *terraform.EvalMaybeTainted
2020/11/11 12:16:16 [TRACE] EvalMaybeTainted: cloudability_view.tbu_test encountered an error during creation, so it is now marked as tainted
2020/11/11 12:16:16 [TRACE] eval: *terraform.EvalWriteState
2020/11/11 12:16:16 [TRACE] EvalWriteState: removing state object for cloudability_view.tbu_test
2020/11/11 12:16:16 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/11/11 12:16:16 [TRACE] EvalApplyProvisioners: cloudability_view.tbu_test has no state, so skipping provisioners
2020/11/11 12:16:16 [TRACE] eval: *terraform.EvalMaybeTainted
2020/11/11 12:16:16 [TRACE] EvalMaybeTainted: cloudability_view.tbu_test encountered an error during creation, so it is now marked as tainted
2020/11/11 12:16:16 [TRACE] eval: *terraform.EvalWriteState
2020/11/11 12:16:16 [TRACE] EvalWriteState: removing state object for cloudability_view.tbu_test
2020/11/11 12:16:16 [TRACE] eval: *terraform.EvalIf
2020/11/11 12:16:16 [TRACE] eval: *terraform.EvalIf
2020/11/11 12:16:16 [TRACE] eval: *terraform.EvalWriteDiff
2020/11/11 12:16:16 [TRACE] eval: *terraform.EvalApplyPost
2020/11/11 12:16:16 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/11/11 12:16:16 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/11/11 12:16:16 [TRACE] [walkApply] Exiting eval tree: cloudability_view.tbu_test
2020/11/11 12:16:16 [TRACE] vertex "cloudability_view.tbu_test": visit complete
2020/11/11 12:16:16 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/skyscrapr/cloudability\"] (close)" errored, so skipping
2020/11/11 12:16:16 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/11/11 12:16:16 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/11/11 12:16:16 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2020/11/11 12:16:16 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2020/11/11 12:16:16 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2020/11/11 12:16:16 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/11/11 12:16:16 [TRACE] statemgr.Filesystem: unlocked by closing terraform.tfstate
2020-11-11T12:16:16.042Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/skyscrapr/cloudability/0.0.6/windows_amd64/terraform-provider-cloudability_v0.0.6.exe pid=19324 error="exit status 2"
2020-11-11T12:16:16.042Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by skyscrapr** [comment]
I haven't tested this against cloudability in 6 months. Let me setup a test account and run the automated tests. Thanks for testing. I'll get back to you later my time this evening NZ time.

**Comment by skyscrapr** [comment]
Quick update. I've setup a test account and I'm building some tests to ensure this is part of CI. Update again in a day or two.

**Comment by petewilcock** [comment]
Thanks sir, your efforts are appreciated! :)

**Comment by petewilcock** [comment]
Let me know if there's any way I can help with this too.

**Comment by skyscrapr** [comment]
Sorry for the delay. Work gets in the way. I'm taking a look at this now. Hope to resolve in the next few hours.

**Comment by petewilcock** [comment]
No problem at all, I really appreciate the efforts and you don't owe me anything :) 

But, I am asking Cloudability to extend official support to your provider, as it's kind of crazy that they haven't already!

**Comment by skyscrapr** [comment]
Took a while to get some test accounts setup. Still working on it.

**Comment by skyscrapr** [comment]
Still haven't got test accounts yet. But I'm working on implementing the acceptance tests and full suite of unit tests. This will make the provider more robust to changes in the API. It will take me some time to resolve. I'll update when you can take a look.

**Comment by skyscrapr** [comment]
This is resolved in latest refactor
